### ISSUE TITLE
Can't use multiple hex codes within 1 message

### ISSUE THREAD

**Issue by mishtavishta** [Sxtanna/vox-chat#2]
When I try to use multiple HEX colour codes within 1 message it seems as though the plugin gets confused and cuts off some of the previously coloured text.

I have attached an image of the message I am trying to type which includes the result, as well as config file.

### Message and result

![image](https://user-images.githubusercontent.com/20979389/168407140-2e48d0a1-85e6-42e1-869d-a7739f123b8f.png)

<details><summary>Config File</summary>
<p>

```yaml
#
# Plugin behavior options
#
 
options:
  # Whether the chat listener will actually cancel the AsyncPlayerChatEvent, or just clear its recipients.
  cancel_chat_event: true
  # Extra features
  extras:
    replacers:
      # Whether the plugin should attempt to replace placeholderapi placeholders
      clip_papi: true
      # Whether the plugin should attempt to replace mvdw_placeholderapi placeholders
      mvdw_papi: true
      # Whether the plugin should attempt to replace items adder font images, ex. :heart:
      items_adder:
        in_formats: true
        in_message: true
  # Format bypassing options
  bypass:
    # Permission for whether a player can always use color codes, regardless of the format
    colors_permission: "voxchat.bypass.colors"
    # Permission for whether a player can always use format codes, regardless of the format
    format_permission: "voxchat.bypass.format"
 
 
#
# Actions are path addressable, reusable component additions.
#
# =======================================
#             Hover Template
# hover:
#   first_name:
#     # A hover with a single line
#     text: "Single Line"
#   other_name:
#     # A hover with multiple lines
#     text:
#       - "multiple"
#       - "lines"
# =======================================
#
# =======================================
#             Click Template
# click:
#   first_name:
#     # Suggest a command to the player
#     show_cmd: "/suggest this command"
#   other_name:
#      # Attempt to open a link in the player's browser
#     open_url: "https://www.google.com"
#   third_name:
#     # Execute a command as the player
#     exec_cmd: "/execute this command"
# =======================================
 
 
actions:
  hover:
    player_info:
      text:
        - "&7- &fName: &a%player_name%"
        - "&7- &fRank: &a%vault_group%"
        - "&7- &fHearts: &a%crown_hearts%"
        - "&7- &fCash: &a$%vault_eco_balance_formatted%"
        - "&7- &fTeam: &a%crown_team%"
        - ""
        - "&7&o(click for more)"
  click:
    message:
      show_cmd: "/stats %player_name%"
    open_store:
      open_url: "https://your.server.store"
    open_stats:
      exec_cmd: "/stats %player_name%"
 
#
# Formats can be assigned via a permission using their name
#
#
# =======================================
#             Format Template
# formats:
#   # Permission would be voxchat.format.default
#   default:
#     allows:
#       # Whether the player can use color codes
#       colors: true # default false
#       # Whether the player can use format codes
#       format: true # default false
#     # The actual format for messages sent by players
#     format: "%player_name% > %message%"
# =======================================
 
formats:
  default:
    allows:
      colors: false
      format: false
    format: "[%vault_prefix%&r %player_name%&r &c%crown_hearts% ❤ &8&l»](hover.player_info,click.open_stats)&r %message%&r"
```

</p>
</details>
